// Package openapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package openapigen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Payment defines model for Payment.
type Payment struct {
	Amount    *string    `json:"amount,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *string    `json:"id,omitempty"`
	Merchant  *string    `json:"merchant,omitempty"`
	Status    *string    `json:"status,omitempty"`
}

// User defines model for User.
type User struct {
	Email *string `json:"email,omitempty"`
	Role  *string `json:"role,omitempty"`
	Token *string `json:"token,omitempty"`
}

// Sort defines model for sort.
type Sort = string

// LoginResponse defines model for LoginResponse.
type LoginResponse = User

// PaymentListResponse defines model for PaymentListResponse.
type PaymentListResponse struct {
	Payments *[]Payment `json:"payments,omitempty"`
}

// UnauthorizedError defines model for UnauthorizedError.
type UnauthorizedError = Error

// PostDashboardV1AuthLoginJSONBody defines parameters for PostDashboardV1AuthLogin.
type PostDashboardV1AuthLoginJSONBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// GetDashboardV1PaymentsParams defines parameters for GetDashboardV1Payments.
type GetDashboardV1PaymentsParams struct {
	// Sort Comma-separated sort fields. Common patterns: `-created_at` (prefix `-` = desc) `amount` (no prefix `-` = asc)
	Sort *Sort `form:"sort,omitempty" json:"sort,omitempty"`

	// Status status of payment (completed , processing , or failed)
	Status *string `form:"status,omitempty" json:"status,omitempty"`

	// Id payment id
	Id *string `form:"id,omitempty" json:"id,omitempty"`
}

// PostDashboardV1AuthLoginJSONRequestBody defines body for PostDashboardV1AuthLogin for application/json ContentType.
type PostDashboardV1AuthLoginJSONRequestBody PostDashboardV1AuthLoginJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Clear cache
	// (POST /clear-cache)
	PostClearCache(w http.ResponseWriter, r *http.Request)
	// Login with email + password
	// (POST /dashboard/v1/auth/login)
	PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request)
	// List of payments
	// (GET /dashboard/v1/payments)
	GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams)
	// Health check
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Clear cache
// (POST /clear-cache)
func (_ Unimplemented) PostClearCache(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login with email + password
// (POST /dashboard/v1/auth/login)
func (_ Unimplemented) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List of payments
// (GET /dashboard/v1/payments)
func (_ Unimplemented) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request, params GetDashboardV1PaymentsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostClearCache operation middleware
func (siw *ServerInterfaceWrapper) PostClearCache(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostClearCache(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDashboardV1AuthLogin operation middleware
func (siw *ServerInterfaceWrapper) PostDashboardV1AuthLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDashboardV1AuthLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboardV1Payments operation middleware
func (siw *ServerInterfaceWrapper) GetDashboardV1Payments(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDashboardV1PaymentsParams

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "id", r.URL.Query(), &params.Id, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboardV1Payments(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/clear-cache", wrapper.PostClearCache)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/dashboard/v1/auth/login", wrapper.PostDashboardV1AuthLogin)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard/v1/payments", wrapper.GetDashboardV1Payments)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWXW/bNhT9KwS3hwZTLHvtQyFgwLJs67qlWLAt20NmLDfUtcVWItlLKq0X+L8Pl5Rt",
	"KZLboAX2ZEu8H+ec+0HdS2UbZw2a4GVxLx0QNBiQ4pO3FPi3RK9Iu6CtkYU8t00Dpx7ZNmAp2EqsNNal",
	"nwk+tEY4CAHJ+ELcnCpCtvsHwo144ghX+r24Ob0R3wiOeyJuoLGt4UNjxeAcvDr528hMas77tkXayEwa",
	"aFAWCVwmvaqwAUaJ76FxNR/1UspMho2L9oG0WcvtdptJQu+s8RhZXti1Nr91b/iFsiagiczBuVorYOb5",
	"a8/073sZvyRcyUJ+kR9EzNOpz688Uko2VI8wtGREsG/QCDClaD2S0GZlqYl55DaTl7Bp0IQL7cMnAXNk",
	"HVLQ2BU1Rov/dcDGfwx7l56RdOIBEWzk9vDC3r5GFaYIds6CwXOEKwNtqCzpf7H8gcjSI5h0pYxA2+iP",
	"JrARlpFo2zRAG1nIV9p7bdbCsoR3UOsyKSszeQd126lWoiyezReZbNB7WDP+q2HUQjTHIkWKj6t5ojeh",
	"ydkhl7ZGrEDXWHKqXVZFWLIB1F4e8kX+e82GRU2sel0fCXbV0SbgmvuvR7k/II9nPx4fnp63rSYuxXWC",
	"cciyHDXIvpnHFNLcD5FBrRV+2z3PlG3GCDLZG+/iXqbJkYUsIeBp0A1O+ehymGgxZdQgqQoeYnrVvRVn",
	"Uz4+QGj90IN7o0ZejplwZBUmdTPWNxV/UtiRdHGJjHTDBnTNf0ZYyNY4eZCKOT6ZGOhMelQt6bD5nZsw",
	"pbxFICRu48PTjzvdf/7rj90i5kjp9ECwCsGloeAtF0HokITdvLAXYNZnzomzy5c8tEg+jcxiNp/NGbp1",
	"aMBpWcins/nsqcykg1BFVLmqEehUgaoibWd9LB2LFSftZckLyfpwzobn0e7B9v96Ph9fcb/+wpmfzRfH",
	"Jn4fIh+vt76Esrgeine93C6z3gKLwERiwI55Cb66tUBlfrfIOXRe8/30YXrf75z+XHCaeKPJNKjow3e2",
	"3HzG9XG83Rx4/85SOd1Y/TWRYvQ8lpM3ycElUIvb6VJ9uB7D2/wzq7gvU4wq3ulQiUhFfCX2VMZl61+4",
	"a5yo2Qvsl+xyZ54Nvr+up0EfTPL4CbTNHnZv2kjCrkQHRDz5+EI6OfaZldZb/woclfohgF1aXR4JGg+O",
	"B1x+SuGnvpn+pyHmnD250xWeVwh12pfHeuCnZPHYjTToyOQrVIXqTfeNgnS3a5yW6m7zFnleWwV1ZX0o",
	"ns+fz+V2uf0vAAD//wMz5/n3CwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
